### ISSUE TITLE
Comment content extra slashed

### ISSUE THREAD

**Issue by kraftbj** [pfefferle/wordpress-semantic-linkbacks#97]
Editing a comment with an apostrophe with this plugin active will extra slash it, e.g. `I'll see you later` becomes `I\'ll see you later`.

Haven't tracked down to where this is happening yet.

**Comment by kraftbj** [comment]
It's apparently coming from `$commentdata = array_merge( $commentdata, $commentarr );` in the `enhance` function ( https://github.com/pfefferle/wordpress-semantic-linkbacks/blob/master/includes/class-linkbacks-handler.php#L83 ) when firing on the `wp_update_comment_data` filter. 

Updating it to `$commentdata = array_merge( $commentdata, wp_unslash( $commentarr ) );` resolves it. I haven't read through to understand why that merge is taking place though and why we're merging new processed data with new raw data.

Thoughts?

**Comment by asuh** [comment]
I believe I'm having the same issue but with double quotation marks.

Using the built-in commenting system, comments are adding the backslash character to double quotation marks. I am using WordPress 4.8.2 and Semantic Linkbacks Version 3.4.0.

On the website with this plugin activated, someone goes to a blog post and writes a comment with a set of double quotations. When they submit the comment, the page reloads and shows the comment including backslashes for each double quotation used.

When going to the Dashboard Comments section to manipulate or approve the comment, I edit the comment to delete the backslashes. When I save the corrected comment without the backslashes, on reload it shows the same backslashes that I deleted added back in. If I edit the comment again and make no changes, I then see a total of three backslashes per double quotation. Same process then shows five backslashes. And so on.

The only resolution is the deactivate the plugin.

I haven't tested the above suggested fix but if that works I'd be happy to submit a pull request.

**Comment by dshanske** [comment]
First, did you try 3.5.1?

**Comment by asuh** [comment]
@dshanske I only saw the upgrade to 3.5.1 not long ago so I upgraded and tried it. I now cannot reproduce this issue so I assume it was fixed with one of the last versions. As long as @kraftbj verifies the same fix, I think this issue is resolved.

**Comment by chrisaldrich** [comment]
<a href="https://github.com/pfefferle/wordpress-semantic-linkbacks/issues/97" class="u-in-reply-to"></a>I just upgraded and can confirm that this is fixed on my site now as well. Thanks folks!

**Comment by pfefferle** [comment]
so I close this for now... please reopen if issue still exists...
